### ISSUE TITLE
Speculative (cached) inputs may cause sprurious errors

### ISSUE THREAD

**Issue by sinelaw** [ElastiLotem/buildsome#17]
When assuming that an output has input 'x' (based on the dependencies cache), if the dependencies changed so that there is actually now no dependency on 'x', we will end up building 'x' for no reason. This is not just a performance issue, it may cause an error if 'x' can't be built, thus failing the build for no reason.

**Comment by ElastiLotem** [comment]
The no-reason part is an inherent choice between over-speculation and rediscovering dependencies expensively.
