### ISSUE TITLE
Assertions in fs_override are not user friendly

### ISSUE THREAD

**Issue by sinelaw** [ElastiLotem/buildsome#49]
I had an assertion (file path) trigger in fs_override.c, but there's no indication in any error message that there's a dir "/tmp/fs_override.so.log" , so I didn't know about it until reading the source code.

Maybe it's ok after all to print error messages also to the process' stderr?

**Comment by ElastiLotem** [comment]
Who says stderr is not some app level pipe? Malicious environment is hard..
:)

I think we can add it to the client server protocol instead.

**Comment by ElastiLotem** [comment]
The assertions now output to the build log itself in red, very friendly! :)
